FROM openjdk:17-jdk-slim        Choose base image
WORKDIR /app            Set working directory
COPY --from=build /app/target/myapp.jar app.jar         Copy only final JAR from build stage
EXPOSE 8080         Expose port (optional)
ENV JAVA_OPTS=""        Environment variables (optional)
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]         Command to run the app